"use client";

import { Zap, Tag, CheckSquare, Globe } from "lucide-react";

export default function TaskCenterPage() {
    return (
        <div className="space-y-12">
            <div>
                <div className="flex items-center gap-3 mb-4">
                    <Zap className="w-8 h-8 text-blue-500" />
                    <h1 className="text-3xl font-black tracking-tight text-zinc-900 dark:text-white">
                        Task Center
                    </h1>
                </div>
                <p className="text-lg text-zinc-600 dark:text-zinc-400 leading-relaxed max-w-2xl">
                    The Task Center is your intelligent inbox. Unlike standard to-do lists, these tasks are proactively generated by the Magic Agent based on real-time market signals.
                </p>
            </div>

            <hr className="border-zinc-200 dark:border-white/10" />

            <div className="grid md:grid-cols-2 gap-6">
                
                {/* Feature 1 */}
                <div className="p-6 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/50">
                    <div className="w-10 h-10 rounded-lg bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 flex items-center justify-center mb-4">
                        <Globe className="w-5 h-5" />
                    </div>
                    <h3 className="text-lg font-bold text-zinc-900 dark:text-white mb-2">Web Analysis Tasks</h3>
                    <p className="text-zinc-600 dark:text-zinc-400 text-sm">
                        When you analyze a competitor's website, the agent creates specific tasks like "Draft Counter-Argument Post" or "Update Landing Page Copy" based on findings.
                    </p>
                </div>

                {/* Feature 2 */}
                <div className="p-6 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/50">
                    <div className="w-10 h-10 rounded-lg bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 flex items-center justify-center mb-4">
                        <Tag className="w-5 h-5" />
                    </div>
                    <h3 className="text-lg font-bold text-zinc-900 dark:text-white mb-2">Source Tagging</h3>
                    <p className="text-zinc-600 dark:text-zinc-400 text-sm">
                        Every task is tagged with its origin. You'll see a small pill (e.g., <span className="bg-zinc-200 dark:bg-zinc-800 px-1 py-0.5 rounded text-xs font-mono">CompetitorX.com</span>) allowing you to trace why a task exists.
                    </p>
                </div>

            </div>

             <section className="space-y-6">
                <h2 className="text-2xl font-bold flex items-center gap-3 text-zinc-900 dark:text-white">
                    <CheckSquare className="w-6 h-6 text-zinc-400" />
                    Actioning Tasks
                </h2>
                <p className="text-zinc-600 dark:text-zinc-400">
                    Tasks are designed for speed. Most tasks include a primary action button like <strong>"Draft Post"</strong> which immediately opens the content editor with context pre-loaded.
                </p>
                <div className="bg-white dark:bg-black border border-zinc-200 dark:border-zinc-800 p-4 rounded-lg shadow-sm max-w-md">
                    <div className="flex items-start justify-between">
                        <div>
                             <h4 className="font-semibold text-sm">Post about new feature</h4>
                             <p className="text-xs text-zinc-500 mt-1">Based on recent competitor announcement</p>
                        </div>
                        <button className="bg-zinc-900 dark:bg-white text-white dark:text-black text-xs font-medium px-3 py-1.5 rounded-lg">
                            Draft
                        </button>
                    </div>
                </div>
            </section>
        </div>
    );
}
